database:
  mysql: false
  username: 'root'
  password: 'password'
settings:
  money-symbol: '$'
  # How many decimal places does your economy support.
  decimal-places: 2
  # If false prices will be truncated (cutoff) after x decimal places (decimal-places above)
  # If true price will be rounded to the nearest decimal place defined by decimal-places value.
  #   If the decimal is 5 (middle) it will round the even number (Banker's Rounding)
  price-rounding: false
  # How much the price increases or decreases by (based off of starting price)
  # The value is a percentage. Default = 0.03 = 3%
  default-price-step: 0.03
  # How much cheaper sell price is from buy price as a percentage. 0.1 = 10%
  buy-sell-difference: 0.0
  # Number of seconds between shop resets
  # When shops' stock resets, money resets, and prices change accordingly
  shop-reset-interval: 1800
  # How many unique players there needs to be for the price to be affected
  # Prevents one player from making the price change
  unique-player-transaction-threshold: 3