name: MCCommodities
main: com.tchristofferson.mccommodities.MCCommodities
version: 1.0
api-version: 1.13
author: tchristofferson
website: https://github.com/tchristofferson/MCCommodities

depend:
  - Vault

softdepend:
  - Citizens